feat(gms): store update events in a new index in ElasticSearch
neojunjie/datahub pull request #135
Opened 2023-11-07 09:50 UTC by danielkoh94

Objective was to capture update events in ElasticSearch for metric-gathering purposes.

This PR makes the following changes:
- Creation of a ElasticSearch index, datahub-update-index
- Process events that are UPSERTs into JSON format that captures information such as time of the event, actor, aspect and entity urn
- Create a request for ElasticSearch to insert the new event into its index.

2023-11-15 01:09 UTC, neojunjie requested changes

2023-11-15 01:09 UTC, neojunjie commented on metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
> +        + event.getAspect().getValue().asAvroString()
since you are using time and content as the hash, it is almost certain that it will result in a new doc. it is unlikely that there will be any update to the document

2023-11-20 03:03 UTC, danielkoh94 commented on metadata-service/restli-servlet-impl/src/main/resources/index/usage-event/update_event_template.json
> +        },
Fields such as urn and other info are automatically indexed by ES when inserting the document into the index so I did not defined them here. Should I define the fields here so it is more transparent?

2023-11-20 03:04 UTC, danielkoh94 commented on metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
> +        + event.getAspect().getValue().asAvroString()
> why do we need to create a unique id for the ES documents? are we not storing each events related to the dataset? can we just use the _id generated by ES?

The ES client in java does not automatically assign a _id to the document, so I need to create a unique _id for each event if not there is an error in uploading the document to the index.

2023-11-20 03:05 UTC, danielkoh94 commented on metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
> +        + event.getAspect().getValue().asAvroString()
> since you are using time and content as the hash, it is almost certain that it will result in a new doc. it is unlikely that there will be any update to the document

Yes, that is the idea here, where each update event is an individual document so we can track all updates over a time period.

2023-11-20 08:02 UTC, neojunjie commented on metadata-service/restli-servlet-impl/src/main/resources/index/usage-event/update_event_template.json
> +        },
are you saying that it is using dynamic-mapping? I think we should define the fields since the schema is known. 
I am wondering if we should use static mapping for this index? With dynamic-mapping, there is no control over what is being sent to the ES for this index. Just need 1 person to send 1 erroneous document with many many fields, it will result in fields explosion in this index. And the mapping is not optimized, I believe each field will have 2 types "keyword" and "text" (waste ram and storage).

2023-11-20 08:05 UTC, neojunjie commented on metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
> +        + event.getAspect().getValue().asAvroString()
https://www.javadoc.io/doc/org.elasticsearch/elasticsearch/7.8.0/org/elasticsearch/action/index/IndexRequest.html#id()

what if you do not set the id for the document? will ES generate the id for you? Lets see if we can use autogenerated ID

2023-11-20 09:13 UTC, danielkoh94 commented on metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
> +        + event.getAspect().getValue().asAvroString()
Hmm auto generated id works. I have removed the relevant parts to make use of the auto generated ID

2023-11-22 00:23 UTC, neojunjie approved these changes

2023-11-22 00:58 UTC, merged