[Feat] edit containers/display panel
neojunjie/datahub pull request #69
Opened 2022-06-02 08:10 UTC by xiphl

1. Took the opportunity to refactor commonly used functions, hence the edit panels are all modified to some extend in this PR.
2. hide the validation tab since we're not using it
3. parent container of selected container will not be shown in the edit panel (think wait for the next release). For now, the user will need to do a container search and only containers that belong to the platform will be pulled. To facilitate testing, I wrote some scripts in metadata-ingestion/examples/library to create/assign containers/domains.
4. had to register container as an entity in test, to solve the issue of entity registry not knowing about containers.
5. added 2 more endpoints for ingest-api. Also, will modify /make_dataset endpoint to auto set the display name.

When the next upstream is pulled, I will explore reducing the duration of the access token (since there is a PR that will allow user to view and revoke existing tokens). Else, everytime the user visits the edit page, a new token is generated periodically and he/she will see a very long list of expiring tokens. Or we could just ask user to not visit the token management page if he/she just made alot of edits in UI lolz.

For now, the endpoints on ingest-api creates a mix of MCP and MCEs. I will update the code if MCP is confirmed the way to go.

2022-06-02 08:19 UTC, xiphl commented
the weird quickstart-compose-validation test failing is a Github wide issue discussed here:
https://github.com/myoung34/docker-github-actions-runner/issues/113

2022-06-06 03:43 UTC, xiphl commented
change the structuring of the panel, to simplify the create_form portion, closing for now.

2022-06-08 02:42 UTC, xiphl commented
not for merging yet

2022-06-08 03:00 UTC, xiphl commented
ok this PR contains all the changes necessary for edit panel - container and display name. create form will be the other PR.

2022-06-08 06:55 UTC, neojunjie requested changes

2022-06-08 06:55 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/ApiCallUtils.tsx
> +    message.success(`Status:${status} - Request submitted successfully. Reloading Page..`, 3).then();
this method should be purely doing print success message. is it a must to put await timeout?

can we doing something like this in the axios method?

axios
            .post(updateUrl, submission)
            .then((response) => { 
printSuccessMsg(response.status) 
window.location.reload();
} )
            .catch((error) => {
                printErrorMsg(error.toString());
            });

2022-06-08 06:55 UTC, neojunjie commented on metadata-ingestion/examples/library/add_new_container.py
> +# event = MetadataChangeProposalWrapper(
remove unnecessary comments pls

2022-06-08 06:55 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/containerEdit/SetParentContainer.tsx
> +                        required: props.compulsory,
is this rule is for parent container? So is it a optional or compulsory field ar?

2022-06-08 06:55 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/containerEdit/EditParentContainerPanel.tsx
> +    const [modifiedState, setModifiedState] = useState(true);
shouldnt it be useState(false) for the start ?

2022-06-08 06:55 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/containerEdit/EditParentContainerPanel.tsx
> +        setModifiedState(false);
setModifiedState(true)

2022-06-08 06:55 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/containerEdit/EditParentContainerPanel.tsx
> +        setModifiedState(true);
setModifiedState(false)?

2022-06-08 06:55 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/containerEdit/EditParentContainerPanel.tsx
> +                <Button type="primary" htmlType="submit" disabled={modifiedState}>
{!modifiedState}

2022-06-08 06:55 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/containerEdit/EditParentContainerPanel.tsx
> +            .then((response) => printSuccessMsg(response.status))
have to call setModifiedState to reset the state after your call to updateurl

2022-06-08 06:55 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/Name/EditDisplayName.tsx
> +    const [modifiedState, setModifiedState] = useState(true);
initial modifiedState should be false right?

2022-06-08 06:55 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/Name/EditDisplayName.tsx
> +        setModifiedState(true);
setModifiedState(false);

2022-06-08 06:55 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/Name/EditDisplayName.tsx
> +        const hasBeenModified = formState.getFieldValue('displayName') === (existingProperties?.name || '');
are we comparing field value ('displayname') against existing name or empty string?
Mmmm weird that we are checking against empty string?

shouldnt we do something like this:
const hasBeenModified = formState.getFieldValue('displayName') === (existingProperties?.name);
setModifiedState(hasBeenModified);

2022-06-08 06:55 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/Name/EditDisplayName.tsx
> +                <Button type="primary" htmlType="submit" disabled={modifiedState}>
<Button type="primary" htmlType="submit" disabled={!modifiedState}>

2022-06-08 08:36 UTC, xiphl commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/containerEdit/SetParentContainer.tsx
> +                        required: props.compulsory,
it is optional for "create dataset" and compulsory for "edit container"

2022-06-08 08:41 UTC, xiphl commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/containerEdit/SetParentContainer.tsx
> +                        required: props.compulsory,
you can't remove a container once its applied, without messing with mySQL directly. You can only change containers. (At least, not in our present version, not sure if upstream got resolve this issue)

2022-06-08 08:59 UTC, xiphl commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/ApiCallUtils.tsx
> +    message.success(`Status:${status} - Request submitted successfully. Reloading Page..`, 3).then();
ok

2022-06-08 09:04 UTC, xiphl commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/Name/EditDisplayName.tsx
> +        const hasBeenModified = formState.getFieldValue('displayName') === (existingProperties?.name || '');
it is possible that existingProperties?.name is undefined because our current existing datasets do not have the name attribute.

2022-06-08 09:14 UTC, neojunjie commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/Name/EditDisplayName.tsx
> +        const hasBeenModified = formState.getFieldValue('displayName') === (existingProperties?.name || '');
Mmmm then we can check for undefined and null first before we compare the value

if (variable !== undefined && variable !== null) {
     // check field value "displayname"
}

2022-06-08 09:45 UTC, xiphl commented on datahub-web-react/src/app/entity/shared/tabs/Dataset/containerEdit/EditParentContainerPanel.tsx
> +            .then((response) => printSuccessMsg(response.status))
if you reload the window it should default back to the initial state, but ok, setModifiedState is called anyway

2022-06-10 10:01 UTC, neojunjie commented
// will this works?

const updateForm = () => {
if (existingProperties?.name !== formState.getFieldValue('displayName') {
setModifiedState(true);
}

// !formState.getFieldValue('displayName') to check for empty value
<Button type="primary" htmlType="submit" disabled={!modifiedState || !formState.getFieldValue('displayName')}>
};

2022-06-12 08:17 UTC, xiphl commented
this feature shd be good to go

2022-06-13 01:59 UTC, neojunjie approved these changes

2022-06-13 01:59 UTC, merged